name: Hello Custom
on: workflow_dispatch

inputs:
  name:
    description: "Nom de l'utilisateur"
    required: false
    default: "World"
  greeting:
    description: "Salution personnalisée"
    required: false
    default: "Hello"
outputs:
  message:
    description: "Le message généré par l'action"
runs:
  using: "node16"
  main: "index.js"